*** Variables ***
${API_URL}=                         http://my.massa

${WALLET_NICKNAME}=                 innonet

${STATUS_OK}=                       200
${STATUS_CREATED}=                  201
${STATUS_ACCEPTED}=                 202
${STATUS_NO_CONTENT}=               204
${STATUS_BAD_REQUEST}=              400
${STATUS_NOT_FOUND}=                404
${STATUS_UNPROCESSABLE_ENTITY}=     422
${STATUS_INTERNAL_SERVER_ERROR}=    500
${STATUS_NOT_IMPLEMENTED}=          501
