#!/bin/bash

# `set -e` causes the script to exit if any command fails.
set -e

# Config script for Massa Station installer on Linux.
# If needed, it displays Massa Station terms and conditions and asks user to agree.

# Source debconf library
. /usr/share/debconf/confmodule


display_terms_and_condition_agreement() {
    db_fset massastation/terms-and-conditions seen false

    db_input critical massastation/terms-and-conditions || true
    db_go || true

    db_get massastation/terms-and-conditions
    # $RET corresponds to the value of the last db_get.
    TERMS_SELECTION=$RET

    if [ "$TERMS_SELECTION" = "true" ]; then
        rm -f /usr/local/share/massastation/display_terms_and_conditions
        touch /usr/local/share/massastation/agreed_to_terms_and_conditions
        exit 0
    else
        echo "You must agree to the terms and conditions to install MassaStation."
        exit 1
    fi
}

display_terms_and_condition_agreement
