linters:
  disable:
    # unwanted
    - nonamedreturns
    - paralleltest
    - testpackage
    - exhaustruct
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - goerr113 # we should decide first on how we would like to handle error internally
    - ireturn
    - depguard

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - unused

run:
  skip-dirs:
    - pkg/front
    - pkg/sc
    - api/swagger/server
    - resource

linters-settings:
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: true
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
