version: '3'

tasks:
  install:
    cmds:
      - echo "Installing dependencies"
      - cmd: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev javascriptcoregtk-4.1-dev build-essential pkg-config
        platforms: [linux]
        ignore_error: true
      - cmd: go install github.com/wailsapp/wails/v3/cmd/wails3@latest
      - cmd: go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - cmd: go install golang.org/x/tools/cmd/stringer@latest
      - cmd: go install go.uber.org/mock/mockgen@v0.2.0

  install-dev:
    cmds:
      - cmd: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3
      - cmd: go install github.com/daixiang0/gci@latest
      - cmd: go install mvdan.cc/gofumpt@latest
      - task: install-dev-win

  install-dev-win:
    platforms: [windows]
    cmds:
      - cmd: mkdir -p build/massastation
      - cmd: curl -o build/massastation/mar-tools-win64.zip https://archive.torproject.org/tor-package-archive/torbrowser/12.5.1/mar-tools-win64.zip

  generate: go generate ./...

  test: 
    cmds:
      - cmd: go test -v -timeout 60s ./...

  test-2e2:
    cmds:
      - cmd: scripts/test-e2e.sh

  test-coverage: 
    cmds:
      - cmd: go test -timeout 60s ./... -coverprofile=coverage.coverprofile

  fmt:
    cmds:
      - cmd: go mod tidy
      - cmd: gofumpt -l -w .
      - cmd: gci write .
      - task: fmt-web
      - cmd: golangci-lint run --fix

  fmt-web:
    dir: web/massastation
    cmds:
      - cmd: npm run fmt

  build:
    cmds:
      - task: build-linux
      - task: build-macos
      - task: build-windows

  build-linux:
    platforms: [linux]
    cmds:
      - cmd: mkdir -p build/massastation
      - cmd: go build -o build/massastation/massastation ./main.go
      - cmd: sudo setcap CAP_NET_BIND_SERVICE=+eip build/massastation/massastation

  build-macos:
    platforms: [darwin]
    cmds:
      - cmd: mkdir -p build/massastation
      - cmd: go build -o build/massastation/massastation ./main.go
    env:
      MACOSX_DEPLOYMENT_TARGET: 11.0

  build-windows:
    platforms: [windows]
    cmds:
      - cmd: mkdir -p build/massastation
      - cmd: mkdir -p build/massastation/logs
      - cmd: mkdir -p build/massastation/certs
      - cmd: go build -o build/massastation/massastation.exe ./main.go

  run:
    env:
      LOG_LEVEL: DEBUG
    cmds:
      - cmd: ./build/massastation/massastation
        platforms: [linux, darwin]
      - cmd: ./build/massastation/massastation.exe
        platforms: [windows]

  build-run:
    cmds:
      - task: build
      - task: run

  all:
    cmds:
      - task: install
      - task: generate
      - task: build-run
