version: "3"

vars:
  APP_NAME: "massastation"
  BIN_DIR: "./build/{{.APP_NAME}}"

includes:
  darwin: tasks/Taskfile_darwin.yml
  linux: tasks/Taskfile_linux.yml
  windows: tasks/Taskfile_windows.yml
  internal: 
    taskfile: tasks/Taskfile_internal.yml
    internal: true

tasks:
  install:
    cmds:
      - echo "Installing dependencies"
      - cmd: go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - cmd: go install golang.org/x/tools/cmd/stringer@latest
      - cmd: go install go.uber.org/mock/mockgen@v0.2.0

  install-dev:
    cmds:
      - cmd: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3
      - cmd: go install github.com/daixiang0/gci@latest
      - cmd: go install mvdan.cc/gofumpt@latest
      - task: install-dev-win

  install-dev-win:
    platforms: [windows]
    cmds:
      - cmd: mkdir -p build/massastation
      - cmd: curl -o build/massastation/mar-tools-win64.zip https://archive.torproject.org/tor-package-archive/torbrowser/12.5.1/mar-tools-win64.zip

  generate: go generate ./...

  test:
    cmds:
      - cmd: go test -v -timeout 60s ./...

  test-2e2:
    cmds:
      - cmd: scripts/test-e2e.sh

  test-coverage:
    cmds:
      - cmd: go test -timeout 60s ./... -coverprofile=coverage.coverprofile

  fmt:
    cmds:
      - cmd: go mod tidy
      - cmd: gofumpt -l -w .
      - cmd: gci write .
      - task: fmt-web
      - cmd: golangci-lint run --fix

  fmt-web:
    dir: web/massastation
    cmds:
      - cmd: npm run fmt

  run:
    summary: Runs MassaStation in DEBUG mode
    cmds:
      - cmd: "{{.BIN_DIR}}/{{.APP_NAME}}{{.BIN_EXT}}"
    vars:
      BIN_EXT: '{{if eq .OS "windows"}}.exe{{end}}'
    env:
      LOG_LEVEL: DEBUG

  build-run:
    cmds:
      - task: build
      - task: run

  all:
    cmds:
      - task: install
      - task: generate
      - task: build-run

  build:
    summary: Builds MassaStation
    cmds:
      - task: linux:int-build
      - task: darwin:int-build
      - task: windows:int-build

  package:
    summary: Packages MassaStation using fyne
    platforms: [linux, darwin]
    cmds:
      - cmd: fyne package -name MassaStation -icon ./int/systray/embedded/logo.png -appID net.massalabs.massastation -exe massastation
