// Code generated by go-swagger; DO NOT EDIT.

// Package restapi thyra-server
//
//  Thyra HTTP server API.
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.0.0
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - image/png
//    - text/css
//    - text/html
//    - application/json
//    - text/webp
//
// swagger:meta
package restapi
