// Code generated by go-swagger; DO NOT EDIT.

// Package restapi thick-client
//
//  Thick client HTTP server API.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
