@startuml Delete request
participant "End user" as user
participant "Browser" as ui
participant "Thyra server" as thyra
participant "Wallet" as w
participant "Node (API)" as node
title "= **Wallet deletion**"

user -> thyra: DELETE a wallet request 
thyra -> w: DELETE /plugin/wallet/{nickname}
w -> w: does this nickname exist?
alt No wallet selected
    w -> thyra: KO response - Wallet-2001
    thyra -> ui: display Wallet-2001 error 
    ui -> user: Error Wallet-2001 displayed 
end
w -> w: are key pair deleted?
alt wallet deletion fail
    w -> thyra: KO response - Wallet-2002 error
    thyra -> ui: display Wallet-2002 error
    ui -> user: Error Wallet-2002 displayed
end
w -> thyra: OK response - success
thyra -> ui: delete wallet info
ui -> user: wallet info deleted
@enduml
