name: Sign a given file with DigiCert KeyLocker

description: Uses DigiCert KeyLocker to sign a file with signtool

inputs:
  file:
    required: true
    description: The file to sign
  SM_API_KEY:
    required: true
    description: The API key for DigiCert KeyLocker
  SM_CLIENT_CERT_FILE_B64:
    required: true
    description: Base64 encoded client certificate file
  SM_CLIENT_CERT_PASSWORD:
    required: true
    description: Password for the client certificate
  SM_HOST:
    required: true
    description: Host for DigiCert KeyLocker
  SM_CERT_FINGERPRINT:
    required: true
    description: Fingerprint of the certificate to use for signing

runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Windows only"
        exit 1

    - name: Install DigiCert Client tools
      uses: digicert/ssm-code-signing@v1.0.1

    - name: Decode and save client certificate
      shell: bash
      run: |
        echo "${{ inputs.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/client_cert.p12

    - name: Sync certs with DigiCert KeyLocker
      shell: cmd
      run: smctl windows certsync
      env:
        SM_CLIENT_CERT_FILE: D:\client_cert.p12
        SM_API_KEY: ${{ inputs.SM_API_KEY }}
        SM_HOST: ${{ inputs.SM_HOST }}
        SM_CLIENT_CERT_PASSWORD: ${{ inputs.SM_CLIENT_CERT_PASSWORD }}
        SM_CERT_FINGERPRINT: ${{ inputs.SM_CERT_FINGERPRINT }}

    # - name: DigiCert healthcheck
    #   shell: cmd
    #   run: smctl healthcheck
    #   env:
    #     SM_CLIENT_CERT_FILE: D:\client_cert.p12
          # SM_API_KEY: ${{ inputs.SM_API_KEY }}
          # SM_HOST: ${{ inputs.SM_HOST }}
          # SM_CLIENT_CERT_PASSWORD: ${{ inputs.SM_CLIENT_CERT_PASSWORD }}
          # SM_CERT_FINGERPRINT: ${{ inputs.SM_CERT_FINGERPRINT }}

    - name: Sign file with signtool
      shell: cmd
      run: |
        signtool.exe sign ^
          /sha1 ${{ env.SM_CERT_FINGERPRINT }} ^
          /tr http://timestamp.digicert.com ^
          /td SHA256 ^
          /fd SHA256 ^
          "${{ inputs.file }}"
      env:
        SM_CLIENT_CERT_FILE: D:\client_cert.p12
        SM_API_KEY: ${{ inputs.SM_API_KEY }}
        SM_HOST: ${{ inputs.SM_HOST }}
        SM_CLIENT_CERT_PASSWORD: ${{ inputs.SM_CLIENT_CERT_PASSWORD }}
        SM_CERT_FINGERPRINT: ${{ inputs.SM_CERT_FINGERPRINT }}

    - name: Verify signature
      shell: cmd
      run: signtool verify /pa /v "${{ inputs.file }}"
