name: Sign a given file with DigiCert KeyLocker

description: Uses DigiCert official GitHub Action to sign a file.

inputs:
  file:
    required: true
    description: The file to sign
  name:
    required: true
    description: The name of the application to sign
  SM_API_KEY:
    required: true
    description: DigiCert API key
  SM_CLIENT_CERT_FILE_B64:
    required: true
    description: Base64-encoded authentication certificate (.p12)
  SM_CLIENT_CERT_PASSWORD:
    required: true
    description: Password for the client cert
  SM_HOST:
    required: true
    description: DigiCert ONE host URL
  SM_CERT_FINGERPRINT:
    required: true
    description: Certificate fingerprint for signing

runs:
  using: "composite"
  steps:
    - name: Install DigiCert Client tools
      uses: digicert/ssm-code-signing@v1.0.0

    - name: Decode and save client certificate
      shell: bash
      run: |
        echo "${{ inputs.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/client_cert.p12

    - name: Set environment variables
      shell: bash
      run: |
        echo "SM_API_KEY=${{ inputs.SM_API_KEY }}" >> "$GITHUB_ENV"
        echo "SM_CLIENT_CERT_PASSWORD=${{ inputs.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV"
        echo "SM_CLIENT_CERT_FILE=D:\\client_cert.p12" >> "$GITHUB_ENV"
        echo "SM_HOST=${{ inputs.SM_HOST }}" >> "$GITHUB_ENV"

    - name: Sign file
      shell: cmd
      run: |
        smctl sign --fingerprint ${{ inputs.SM_CERT_FINGERPRINT }} --input ${{ inputs.file }}
