name: Sign a given file with DigiCert KeyLocker

description: Uses DigiCert KeyLocker (via smctl) to sign a file.

inputs:
  file:
    required: true
    description: The file to sign
  name:
    required: true
    description: The name of the application to sign
  SM_API_KEY:
    required: true
    description: DigiCert API key
  SM_CLIENT_CERT_FILE_B64:
    required: true
    description: Base64-encoded authentication certificate (.p12)
  SM_CLIENT_CERT_PASSWORD:
    required: true
    description: Password for the client cert
  SM_CERT_FINGERPRINT:
    required: true
    description: Certificate fingerprint for signing

runs:
  using: "composite"
  steps:
    - name: Download smctl
      shell: bash
      run: |
        curl -L -o smctl.zip "https://[TON_URL]/smctl-windows.zip"
        unzip smctl.zip -d smtools
        chmod +x smtools/smctl
        echo "$GITHUB_WORKSPACE/smtools" >> $GITHUB_PATH

    - name: Decode and install client certificate
      shell: bash
      run: |
        echo "${{ inputs.SM_CLIENT_CERT_FILE_B64 }}" | base64 -d > client_cert.p12

    - name: Authenticate with DigiCert KeyLocker
      shell: bash
      run: |
        smctl auth login \
          --api-key "${{ inputs.SM_API_KEY }}" \
          --client-cert client_cert.p12 \
          --cert-password "${{ inputs.SM_CLIENT_CERT_PASSWORD }}"

    - name: Sign file using DigiCert KeyLocker
      shell: bash
      run: |
        smctl sign code-signing \
          --fingerprint "${{ inputs.SM_CERT_FINGERPRINT }}" \
          --file "${{ inputs.file }}" \
          --name "${{ inputs.name }}" \
          --ts-url "http://timestamp.globalsign.com/tsa/r6advanced1"
