#!/bin/bash

# Postinstall script for MassaStation installer on MacOS
# It configures /etc/hosts to resolve station.massa to localhost, create required folders, install dependencies...

set -e

# Set MassaStation configuration directory.
export MASSASTATION_CONFIG_DIR=/usr/local/share/massastation
export MASSASTATION_CERT_DIR=/etc/massastation/certs

# Print error message to stderr and exit with code 1.
fatal() {
    echo "FATAL: $1" >&2
    exit 1
}

mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/logs || fatal "logs directory creation failed."
mkdir -m 777 -p $MASSASTATION_CERT_DIR || fatal "certs directory creation failed."

# If station.massa is not resolved, we add its redirection to /etc/hosts.
ping -c 1 -t 1 station.massa >/dev/null 2>&1 || echo "127.0.0.1 station.massa" >>/etc/hosts || fatal "failed to set station.massa redirection to localhost."

mv ./uninstall.sh $MASSASTATION_CONFIG_DIR || fatal "uninstall script move failed."

LOG_LEVEL=DEBUG $2/MassaStation.app/Contents/MacOS/massastation --repair || fatal "failed to repair MassaStation"
