#!/bin/bash

# Postinstall script for MassaStation installer on MacOS
# It configures dnsmasq to resolve .massa domains to localhost and other configuration (create folders, install dependencies...)

set -e

# `brew` isn't in $PATH by default in the `.pkg` installer environment.
export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH

# Set MassaStation configuration directory.
export MASSASTATION_CONFIG_DIR=/usr/local/share/massastation
export MASSASTATION_CERT_DIR=/etc/massastation/certs

# Print error message to stderr and exit with code 1.
fatal() {
    echo "FATAL: $1" >&2
    exit 1
}

# ./install_homebrew.sh is a script that installs homebrew if it's not installed. Otherwise it performs a brew update.
./install_homebrew.sh || fatal "failed to install brew"

HOMEBREW_PATH=$(brew --prefix)

# nss contains certutil which is used to generate a certificate.
su - $USER -c "$HOMEBREW_PATH/bin/brew install nss" || fatal "failed to install nss using homebrew"


mkdir -m 777 -p $MASSASTATION_CONFIG_DIR || fatal "config directory creation failed."
mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/plugins || fatal "plugins directory creation failed."
mkdir -m 777 -p $MASSASTATION_CONFIG_DIR/logs || fatal "logs directory creation failed."
mkdir -m 777 -p $MASSASTATION_CERT_DIR || fatal "certs directory creation failed."

# If station.massa is not resolved, we add its redirection to /etc/hosts.
ping -c 1 -t 1 station.massa >/dev/null 2>&1 || echo "127.0.0.1 station.massa" >>/etc/hosts || fatal "failed to set station.massa redirection to localhost."

mv ./uninstall.sh $MASSASTATION_CONFIG_DIR || fatal "uninstall script move failed."

LOG_LEVEL=DEBUG $2/MassaStation.app/Contents/MacOS/massastation --repair || fatal "failed to repair MassaStation"
