#!/bin/bash

# This script is used to uninstall MassaStation from MacOS.
# It will remove the following files:
# - MassaStation App.
# - Certificates generated for MassaStation.
# - MassaStation configuration directory.
# - MassaStation plugins.
# And the redirection of station.massa to localhost in /etc/hosts.

set -e

# Set MassaStation configuration directory.
export MASSASTATION_CONFIG_DIR=/usr/local/share/massastation
export MASSASTATION_CERT_DIR=/etc/massastation/certs

# Print error message to stderr and exit with code 1.
fatal() {
    echo "FATAL: $1" >&2
    exit 1
}

# Warn prints a given message in yellow.
warn() {
    echo -e "\033[1;33m$1\033[0m"
}

remove_station_redirection() {
    echo "Removing station.massa redirection from /etc/hosts..."
    sudo sed -i '' '/station.massa/d' /etc/hosts || fatal "failed to remove station.massa redirection from /etc/hosts."
}

remove_massastation() {
    echo "Removing MassaStation App..."
    sudo rm -rf /Applications/MassaStation.app || fatal "failed to remove MassaStation App."

    echo "Removing MassaStation configuration directory..."
    sudo rm -rf $MASSASTATION_CONFIG_DIR || fatal "failed to remove MassaStation configuration directory."

    echo "Removing MassaStation certificates..."
    sudo rm -rf $MASSASTATION_CERT_DIR || fatal "failed to remove MassaStation certificates."

    remove_station_redirection

    echo "MassaStation was successfully uninstalled. We're sorry to see you go."
}

warn "This script will remove anything related to MassaStation from your system."
warn "This includes the MassaStation App, configuration files, plugins, and every other files generated by MassaStation or it's plugins."
read -p "Are you sure you want to continue? [y/N] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    remove_massastation
    exit 0
else
    fatal "Uninstallation aborted."
fi
