@startuml
participant "End user" as user
participant "Browser" as ui
participant "Thyra server" as thyra
participant "Hosting websites" as web
participant "Wallet" as w
participant "DNS" as dns
participant "Event Manager" as em
participant "Storage" as storage
participant "Node (API)" as node

user -> ui: click on install 'Web on-chain' plug-in
ui -> thyra: GET /plugin/webOnChain
thyra -> web: GET /plugin/webOnChain
web -> thyra: OK response
thyra -> ui: display landing page WebOnChain.massa
ui -> user: display landing page WebOnChain.massa

user -> ui: Click on "websites" page
ui -> thyra: GET /plugin/wallet
thyra -> web: GET /plugin/wallet
web -> thyra: GET /plugin/wallet/{status}
thyra -> w: GET /plugin/wallet/{status}
w -> w: is wallet status active?
w -> thyra: KO response - inactive status
thyra -> web: KO response - inactive status
web -> ui: display KO response - inactive status
ui -> user: Error "Connect to your wallet" displayed
w -> thyra: OK response
web -> w: GET /plugin/wallet/
w -> w: is there any wallet?
w -> web: KO response - Wallet-4001 error
web ->thyra: KO response - Wallet-4001 error
thyra -> ui: display Wallet-4001 error
ui -> user: Error Wallet-4001 displayed
w -> thyra: OK response
thyra -> web: OK response
web -> ui: list of existing wallet
ui -> user: display list of wallet
ui -> thyra: GET /plugin/webOnChain/dns/my/domains/{nickname}
thyra -> web: GET /plugin/webOnChain/dns/my/domains/{nickname}
web -> dns: GET /plugin/webOnChain/dns/my/domains/{nickname}
dns -> node: GET /plugin/webOnChain/dns/dns/my/domain/{nickname}
node -> node: Does any DNS exist on this address?
node -> dns: KO response
dns -> web: KO response - Domain-0001
web -> thyra: KO response - Domain-0001
thyra -> ui: display Domain-0001 error
ui -> user: Error Domain-0001 displayed
node -> node: Is there any websites linked your SC address?
node -> dns: KO response
dns -> thyra: KO response - Domain-0002
thyra -> web: KO response - Domain-0002
web -> ui: display Domain-0002 error
ui -> user: Error Domain-0002 displayed
node -> dns: OK response
dns -> web: OK response 
web -> thyra: OK response
thyra -> ui: display list of DNS owned
ui -> user: list of DNS owned displayed

user -> ui: click on deploy website to Massa (create request)
ui -> thyra: PUT /plugin/webOnchain/website/prepare
thyra -> web: PUT /plugin/webOnchain/website/prepare
web -> thyra: GET /plugin/wallet/operationId
thyra -> w: GET /plugin/wallet/operationId/{nickname}
w -> thyra: GUI password
thyra -> user: GUI password
user -> thyra: Password entry
thyra -> w: Password entry
w -> w: is the password matching?
w -> thyra: KO response - Wallet-0002
thyra -> web: KO response - Wallet-0002
web -> ui: display Wallet-0002 error
ui -> user: Error Wallet-0002 displayed
w -> thyra: OK response
thyra -> web: OK reponse
web -> web: is the file in .zip format?
web -> thyra: KO reponse - WebCreator-1001
thyra -> ui: display WebCreator-1001 error
ui -> user: Error WebCreator-1001 displayed
web -> web: is the size smaller than the limit?
web -> thyra: KO response - WebCreator-1004
thyra -> ui: display WebCreator-1004 error
ui -> user: Error WebCreator-1004 displayed
web -> web: is the index.html at the root?
web -> thyra: KO response - WebCreator-XXXX
thyra -> ui: display WebCreator-XXXX error
ui -> user: Error WebCreator-XXXX displayed
web -> dns: POST /plugin/webOnchain/cmd/executeFunction/ExecuteSC/operationId
dns -> dns: does this domain name already exist?
dns -> web: KO response - WebCreator-XXXX
web -> thyra: KO response - WebCreator-XXXX
thyra -> ui: display WebCreator-XXXX error
ui -> user: Error WebCreator-XXX displayed
dns -> dns: is there any special characters in the domain name?
dns -> web: KO response - WebCreator-XXXX
web-> thyra: KO response - WebCreator-XXXX
thyra -> ui: display WebCreator-XXXX error
ui-> user: Error WebCreator-XXXX displayed
dns -> web: OK response
web -> storage: POST /plugin/webOnchain/websiteCretor/upload/operationId
storage -> node: POST /plugin/webOnchain/cmd/executeFunction/CreateSC/operationId
node -> node: CreateSC
node -> storage: KO response
storage -> web: KO response - WebCreator-XXXX
web -> thyra: KO response - WebCreator-XXXX
thyra -> ui: display KO WebCreator-XXXX error 
ui -> user: Error WebCreator-XXXX displayed
node -> storage: OK response
storage -> node: POST /plugin/webOnchain/cmd/executeFunction/ExecuteSC/operationId
node -> node: ExecuteSC
em -> node: GET /plugin/webOnchain/events/container//operationId/{caller}
node -> node: is the containder deployed?
node -> storage: KO reponse - WebCreator-XXXX
storage -> web: KO response - WebCreator-XXXX
web -> thyra: KO response - WebCreator-XXXX
thyra -> ui: display WebCreator-XXXX error
ui -> user: Error WebCreator-XXXX displayed
node -> storage: OK reponse 
storage -> web: OK response
web -> thyra: OK response
thyra -> ui: display "success message"
ui -> user: "Contrainer deployes" message displayed
em -> node: GET /plugin/webOnChain/events/resolver//operationId//{caller}
node -> node: is the resolver set?
node -> em: KO response - WebCreator-XXXX
em -> web: KO response - WebCreator-XXXX
web -> thyra: KO response - WebCreator-XXXX
thyra -> ui: display WebCreator-XXXX error
ui -> user: Error WebCreator-XXXX displayed
node -> em: OK response
em -> web: OK response 
web -> thyra: OK response
thyra -> ui: display "success message"
ui -> user: "Resolver set" message displayed
em -> node: GET /plugin/webOnchain/events/chunkUpload/operationId/{caller}
node -> node: Does one chunk has been uploaded?
node -> em: KO response
em -> web: KO response
web -> storage: POST /plugin/webOnchain/cmd/executeFunction/ExecuteAppendSC/operationId
storage -> node: ExecuteAppendSC
em -> node: GET /thyra/events/chunk/{caller}
node -> em: OK response
em -> web: OK reponse
web -> thyra: OK reponse
thyra -> ui: display "success message"
ui -> user: "chunk X on Y uploaded" message displayed
node -> em: KO response 
em -> web: KO response - list of non-uploded chunk(s)
web -> thyra: Add website on the table list, display edit button & correction button
thyra -> ui: Add website on the table list, display edit button & correction button
ui -> user: Add website on the table list, display edit button & correction button

user -> ui: click on correction button
ui -> thyra: PUT /plugin/webOnchain/websiteCretor/upload/operationId
thyra -> web: PUT /plugin/webOnchain/websiteCretor/upload/operationId
web -> thyra: GET /plugin/wallet/OperationId/{nickname}
thyra -> w: GET /plugin/wallet/operationId/{nickname}
w -> thyra: GUI password
thyra -> user: GUI password
user -> thyra: Password entry
thyra -> w: Password entry
w -> w: is the password matching?
w -> thyra: KO response - Wallet-0002
thyra -> web: KO response - Wallet-0002
web -> ui: display Wallet-0002 error
ui -> user: Error Wallet-0002 displayed
w -> thyra: OK response
thyra -> web: OK reponse
web -> storage: PUT /plugin/webOnchain/websiteCretor/upload/operationId/{chunk X,Y,Z}
storage -> node: /plugin/webOnchain/cmd/executeFunction/ExecuteSC/operationId/{chunk X,Y,Z}
node -> node: ExecuteSC
em -> node: GET /plugin/webOnChain/events/operationId/chunk/{caller}
node -> node: is chunk x,y,z uploaded?
node -> em: KO response - 
em -> web: KO response -
web -> thyra: KO response -
thyra -> ui: display 
ui -> user: Error displayed
node -> em: OK response - 
em -> web: OK response - 
web -> thyra: OK response - 
thyra -> ui: display "success message"
ui -> user: upload success message displayed
@enduml