name: 'Massa Station install'

inputs:
  os:
    default: 'ubuntu-24.04'
    description: The operating system to install dependencies for
  repo-token:
    description: The token to use to authenticate with the GitHub API
    required: true

runs:
  using: "composite"
  steps:
    - name: installing linux dependencies
      if: startsWith(inputs.os, 'ubuntu-')
      shell: bash
      run: |
        # sudo sed -i 's/^deb/#deb/g' /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        curl https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
        sudo dpkg -i --force-confnew packages-microsoft-prod.deb
        sudo apt update
        sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64 p7zip

    - uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ inputs.repo-token }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: web/massastation/package-lock.json

    - name: install go deps
      shell: bash
      run: task install

    - name: Build react frontend and swagger api
      shell: bash
      run: task generate
