name: 'Massa Station install'

inputs:
  os:
    default: 'ubuntu-20.04'
  repo-token:
    description: The token to use to authenticate with the GitHub API
    required: true

runs:
  using: "composite"
  steps:
    - name: installing linux dependencies
      if: startsWith(inputs.os, 'ubuntu-')
      shell: bash
      run: |
        sudo sed -i 's/^deb/#deb/g' /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt update
        sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64 p7zip

    - uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ inputs.repo-token }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: web/massastation/package-lock.json

    - name: install go deps
      shell: bash
      run: task install

    - name: Build react frontend and swagger api
      shell: bash
      run: task generate
