name: 'Thyra install'

inputs:
  os:
    required: true
    default: 'ubuntu-20.04'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      env:
        GO_VERSION: 1.19
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: installing linux dependencies
      if: startsWith(inputs.os, 'ubuntu-')
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64
