name: 'Thyra install'

inputs:
  os:
    default: 'ubuntu-20.04'

runs:
  using: "composite"
  steps:
    - name: installing linux dependencies
      if: startsWith(inputs.os, 'ubuntu-')
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64 p7zip

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: web/thyra-frontend/package-lock.json

    - name: Build react frontend
      shell: bash
      run: go generate gen-frontend.go
