name: 'Thyra install'

inputs:
  os:
    required: true
    default: 'ubuntu-latest'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      env:
        GO_VERSION: 1.19
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: installing linux dependencies
      if: ${{ inputs.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64
    - name: Install Xcode
      if: ${{ inputs.os == 'macos-latest' }}
      uses: devbotsxyz/xcode-select@v1
