name: Sign a given file

inputs:
  file:
    required: true
    description: The file to sign
  GCP_PEM_KEY:
    required: true
    description: The PEM key to use for signing
  GCP_KEYSTORE_ID:
    required: true
    description: The ID of the keystore to use for signing
  GCP_KEY_ALIAS:
    required: true
    description: The alias of the key to use for signing
  GCP_WORKLOAD_IDENTITY_PROVIDER:
    required: true
    description: The workload identity provider to use for signing
  GCP_SERVICE_ACCOUNT:
    required: true
    description: The service account to use for signing


runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.GCP_SERVICE_ACCOUNT }}

    - name: Download Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Prepapre environment for signature
      shell: bash
      run: |
        curl -L -o jsign.jar https://github.com/ebourg/jsign/releases/download/5.0/jsign-5.0.jar
        echo "${{ inputs.GCP_PEM_KEY }}" > codesign-chain.pem

    - name: Sign massastation with EV cert on Google Cloud
      shell: bash
      run: |
        java -jar jsign.jar --storetype GOOGLECLOUD --storepass "$(gcloud auth print-access-token)" --keystore "${{ inputs.GCP_KEYSTORE_ID }}" --alias "${{ inputs.GCP_KEY_ALIAS }}" --certfile "codesign-chain.pem" --tsmode RFC3161 --tsaurl http://timestamp.globalsign.com/tsa/r6advanced1 ${{ inputs.file }}
