testnet:
  DNS: AS12MGDGVB3xNDqzGidJM5fcAbjF1ZP5XAecm5ww4RU7sfQd4cMKk
  URLs:
    - https://test.massa.net/api/v2
  Default: true

buildnet:
  DNS: AS12aGWkBorEM2EpKeNyigSkoCqwdxm872g5KkzUiox3v4VosFW3F
  URLs:
    - https://buildnet.massa.net/api/v2

labnet:
  DNS: AS1PV17jWkbUs7mfXsn8Xfs9AK6tHiJoxuGu7RySFMV8GYdMeUSh
  URLs:
    - 192.168.2.1
    - 192.168.2.2
