testnet:
  DNS: AS12YMz7NjyP3aeEWcSsiC58Hba8UxHapfGv7i4PmNMS2eKfmaqqC
  URLs:
    - https://test.massa.net/api/v2

buildnet:
  DNS: AS12RsqDwktfxfTygPcxRt9mqoW3kn5sWJvqWLdfLstaTCxJsFvni
  URLs:
    - https://buildernet.massa.net/api/v2
  Default: true


labnet:
  DNS: AS1PV17jWkbUs7mfXsn8Xfs9AK6tHiJoxuGu7RySFMV8GYdMeUSh
  URLs:
    - 192.168.2.1
    - 192.168.2.2
