// GENERATED BY textFileToGoConst
// GitHub:     github.com/logrusorgru/textFileToGoConst
// input file: html\front\wallet.css
// generated:  Thu Sep 29 18:12:47 CEST 2022

package wallet

const CSS = `body {
	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu',
		'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	color: #fff;

	background: linear-gradient(90deg, #172230 50.03%, #0c1219 85.82%);
}

.massa-logo {
	width: 170px;
}

.title-wallet {
	margin-bottom: 45px;
}

.form-control,
.form-control:focus {
	color: white;
	border-radius: 0;
	border: none;
	border-bottom: 2px solid hsla(0, 0%, 100%, 0.2);
	background-color: transparent;
	box-shadow: none;
}

h1 {
	font-size: 3.5rem;
	color: hsla(0, 0%, 100%, 0.2);
}
h2 {
	color: hsla(0, 0%, 100%, 0.2);
}

button {
	border: none;
	padding: 3px 30px;
	border-radius: 100px;
	color: #fff;
}

.primary-button {
	font-size: 1.3rem;
	background-color: #e74e4e;
	border: 3px solid #e74e4e;
}

.secondary-button {
	font-size: 1.3rem;
	background-color: transparent;
	border: 3px solid #3246ff;
}

.table {
	color: white;
}

tbody,
td,
tfoot,
th,
thead,
tr {
	border-color: rgb(86, 86, 86);
}

.table > :not(caption) > * > * {
	padding: 18px 1.5rem;
}

.table-striped > tbody > tr:nth-of-type(odd) > * {
	background-color: hsla(0, 0%, 100%, 0.05);
	color: white;
}

.alert {
	display: none;
	position: fixed;
	top: 20px;
	left: 50%;
	transform: translate(-50%, 0);
	margin: auto;
	width: 300px;
	padding: 10px 0;
	background-color: #e74e4e;
	border: none;
	text-align: center;
	color: white;
}

.clipboard {
	cursor: pointer;
	margin-left: 10px;
	margin-bottom: 4px;
}

.quit-button {
	cursor: pointer;
}
`
