// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAddresses rpc get_addresses call
//
// swagger:model Get_addresses
type GetAddresses struct {

	// the final balances of addresses
	FinalBalances []string `json:"finalBalances"`

	// the pending balances of addresses
	PendingBalances []string `json:"pendingBalances"`
}

// Validate validates this get addresses
func (m *GetAddresses) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get addresses based on context it is used
func (m *GetAddresses) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAddresses) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAddresses) UnmarshalBinary(b []byte) error {
	var res GetAddresses
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
