// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadState Upload state
//
// swagger:model UploadState
type UploadState struct {

	// Last uploaded chunk id
	LastChunk int64 `json:"lastChunk,omitempty"`

	// Upload action status
	Status string `json:"status,omitempty"`

	// Total chunk number
	TotalChunk int64 `json:"totalChunk,omitempty"`
}

// Validate validates this upload state
func (m *UploadState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upload state based on context it is used
func (m *UploadState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadState) UnmarshalBinary(b []byte) error {
	var res UploadState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
