// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Websites Websites object (V0).
//
// swagger:model Websites
type Websites struct {

	// Website's address.
	Address string `json:"address,omitempty"`

	// Array of empty chunks if website contains preventing the website to load.
	HasBrokenChunk []string `json:"hasBrokenChunk"`

	// Website's name.
	Name string `json:"name,omitempty"`
}

// Validate validates this websites
func (m *Websites) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this websites based on context it is used
func (m *Websites) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Websites) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Websites) UnmarshalBinary(b []byte) error {
	var res Websites
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
