// GENERATED BY textFileToGoConst
// GitHub:     github.com/logrusorgru/textFileToGoConst
// input file: html/front/common.js
// generated:  Wed Sep 21 10:06:14 CEST 2022

package front

const Common = "// utils\n\nfunction ellipsis(str) {\n\treturn str.substr(0, 5) + '...' + str.substr(str.length - 5, str.length);\n}\n\nconst copyToClipboard = (\n  value,\n  successfully = () => null,\n  failure = () => null\n) => {\n  const clipboard = navigator.clipboard;\n  if (clipboard !== undefined && clipboard !== \"undefined\") {\n    navigator.clipboard.writeText(value).then(successfully, failure);\n  } else {\n    if (document.execCommand) {\n      const el = document.createElement(\"input\");\n      el.value = value;\n      document.body.append(el);\n\n      el.select();\n      el.setSelectionRange(0, value.length);\n\n      if (document.execCommand(\"copy\")) {\n        successfully();\n      }\n\n      el.remove();\n    } else {\n      failure();\n    }\n  }\n};\n\nconst addressInnerHTML = (address) => `${ellipsis(address)} <svg xmlns=\"http://www.w3.org/2000/svg\" onclick=\"copyToClipboard('${address}')\" style=\"cursor: pointer;\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-back\" viewBox=\"0 0 16 16\"><path d=\"M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2z\"/></svg>`;\n"
