// GENERATED BY textFileToGoConst
// GitHub:     github.com/logrusorgru/textFileToGoConst
// input file: html\front\common.js
// generated:  Wed Sep 21 18:11:23 CEST 2022

package front

const Common = "// utils\r\n\r\nfunction ellipsis(str) {\r\n\treturn str.substr(0, 5) + '...' + str.substr(str.length - 5, str.length);\r\n}\r\n\r\nconst copyToClipboard = (\r\n  value,\r\n  successfully = () => null,\r\n  failure = () => null\r\n) => {\r\n  const clipboard = navigator.clipboard;\r\n  if (clipboard !== undefined && clipboard !== \"undefined\") {\r\n    navigator.clipboard.writeText(value).then(successfully, failure);\r\n  } else {\r\n    if (document.execCommand) {\r\n      const el = document.createElement(\"input\");\r\n      el.value = value;\r\n      document.body.append(el);\r\n\r\n      el.select();\r\n      el.setSelectionRange(0, value.length);\r\n\r\n      if (document.execCommand(\"copy\")) {\r\n        successfully();\r\n      }\r\n\r\n      el.remove();\r\n    } else {\r\n      failure();\r\n    }\r\n  }\r\n};\r\n\r\nconst addressInnerHTML = (address) => `${ellipsis(address)} <svg xmlns=\"http://www.w3.org/2000/svg\" onclick=\"copyToClipboard('${address}')\" style=\"cursor: pointer;\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-back\" viewBox=\"0 0 16 16\"><path d=\"M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2z\"/></svg>`;\r\n"
