// GENERATED BY textFileToGoConst
// GitHub:     github.com/logrusorgru/textFileToGoConst
// input file: html\front\event-manager.js
// generated:  Fri Sep 16 12:26:41 CEST 2022

package front

const EventManager = "class EventManager {\r\n\tasync subscribe(str, address, callback) {\r\n\t\taxios({\r\n\t\t\turl: `/thyra/events/${str}/${address}`,\r\n\t\t\tmethod: 'GET',\r\n\t\t})\r\n\t\t\t.then((operation) => {\r\n\t\t\t\tcallback();\r\n\t\t\t})\r\n\t\t\t.catch((e) => {\r\n\t\t\t\t// RETRY\r\n\t\t\t});\r\n\t}\r\n}\r\n"
