// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewBrowseParams creates a new BrowseParams object
//
// There are no default values defined in the spec.
func NewBrowseParams() BrowseParams {

	return BrowseParams{}
}

// BrowseParams contains all the bound params for the browse operation
// typically these are obtained from a http.Request
//
// swagger:parameters browse
type BrowseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Address containing the website.
	  Required: true
	  In: path
	*/
	Address string
	/*Website resource.
	  Required: true
	  In: path
	*/
	Resource string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewBrowseParams() beforehand.
func (o *BrowseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAddress, rhkAddress, _ := route.Params.GetOK("address")
	if err := o.bindAddress(rAddress, rhkAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	rResource, rhkResource, _ := route.Params.GetOK("resource")
	if err := o.bindResource(rResource, rhkResource, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAddress binds and validates parameter Address from path.
func (o *BrowseParams) bindAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Address = raw

	return nil
}

// bindResource binds and validates parameter Resource from path.
func (o *BrowseParams) bindResource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Resource = raw

	return nil
}
