// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// BrowseHandlerFunc turns a function with the right signature into a browse handler
type BrowseHandlerFunc func(BrowseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BrowseHandlerFunc) Handle(params BrowseParams) middleware.Responder {
	return fn(params)
}

// BrowseHandler interface for that can handle valid browse params
type BrowseHandler interface {
	Handle(BrowseParams) middleware.Responder
}

// NewBrowse creates a new http.Handler for the browse operation
func NewBrowse(ctx *middleware.Context, handler BrowseHandler) *Browse {
	return &Browse{Context: ctx, Handler: handler}
}

/* Browse swagger:route GET /browse/{address}/{resource} browse

Browse browse API

*/
type Browse struct {
	Context *middleware.Context
	Handler BrowseHandler
}

func (o *Browse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewBrowseParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
