// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/thyra/api/swagger/server/models"
)

// CmdDeploySCOKCode is the HTTP code returned for type CmdDeploySCOK
const CmdDeploySCOKCode int = 200

/*
CmdDeploySCOK OK.

swagger:response cmdDeploySCOK
*/
type CmdDeploySCOK struct {

	/*Operation id.
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCmdDeploySCOK creates CmdDeploySCOK with default headers values
func NewCmdDeploySCOK() *CmdDeploySCOK {

	return &CmdDeploySCOK{}
}

// WithPayload adds the payload to the cmd deploy s c o k response
func (o *CmdDeploySCOK) WithPayload(payload string) *CmdDeploySCOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cmd deploy s c o k response
func (o *CmdDeploySCOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CmdDeploySCOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CmdDeploySCBadRequestCode is the HTTP code returned for type CmdDeploySCBadRequest
const CmdDeploySCBadRequestCode int = 400

/*
CmdDeploySCBadRequest Bad request.

swagger:response cmdDeploySCBadRequest
*/
type CmdDeploySCBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCmdDeploySCBadRequest creates CmdDeploySCBadRequest with default headers values
func NewCmdDeploySCBadRequest() *CmdDeploySCBadRequest {

	return &CmdDeploySCBadRequest{}
}

// WithPayload adds the payload to the cmd deploy s c bad request response
func (o *CmdDeploySCBadRequest) WithPayload(payload *models.Error) *CmdDeploySCBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cmd deploy s c bad request response
func (o *CmdDeploySCBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CmdDeploySCBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CmdDeploySCUnprocessableEntityCode is the HTTP code returned for type CmdDeploySCUnprocessableEntity
const CmdDeploySCUnprocessableEntityCode int = 422

/*
CmdDeploySCUnprocessableEntity Unprocessable Entity - syntax is correct, but the server was unable to process the contained instructions.

swagger:response cmdDeploySCUnprocessableEntity
*/
type CmdDeploySCUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCmdDeploySCUnprocessableEntity creates CmdDeploySCUnprocessableEntity with default headers values
func NewCmdDeploySCUnprocessableEntity() *CmdDeploySCUnprocessableEntity {

	return &CmdDeploySCUnprocessableEntity{}
}

// WithPayload adds the payload to the cmd deploy s c unprocessable entity response
func (o *CmdDeploySCUnprocessableEntity) WithPayload(payload *models.Error) *CmdDeploySCUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cmd deploy s c unprocessable entity response
func (o *CmdDeploySCUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CmdDeploySCUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CmdDeploySCInternalServerErrorCode is the HTTP code returned for type CmdDeploySCInternalServerError
const CmdDeploySCInternalServerErrorCode int = 500

/*
CmdDeploySCInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response cmdDeploySCInternalServerError
*/
type CmdDeploySCInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCmdDeploySCInternalServerError creates CmdDeploySCInternalServerError with default headers values
func NewCmdDeploySCInternalServerError() *CmdDeploySCInternalServerError {

	return &CmdDeploySCInternalServerError{}
}

// WithPayload adds the payload to the cmd deploy s c internal server error response
func (o *CmdDeploySCInternalServerError) WithPayload(payload *models.Error) *CmdDeploySCInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cmd deploy s c internal server error response
func (o *CmdDeploySCInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CmdDeploySCInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
