// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewMassaGetAddressesParams creates a new MassaGetAddressesParams object
//
// There are no default values defined in the spec.
func NewMassaGetAddressesParams() MassaGetAddressesParams {

	return MassaGetAddressesParams{}
}

// MassaGetAddressesParams contains all the bound params for the massa get addresses operation
// typically these are obtained from a http.Request
//
// swagger:parameters massaGetAddresses
type MassaGetAddressesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specifies the attributes to return. If no attributes are provided, they are all returned.
	Possible values:

	| Attribute | Content |
	| ----------- | -----------|
	| balance | the pending balances (takes into account pending/non-final operations) and the final balances (takes into account only final operations). |

	  Required: true
	  In: query
	  Collection Format: multi
	*/
	Query []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewMassaGetAddressesParams() beforehand.
func (o *MassaGetAddressesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qQuery, qhkQuery, _ := qs.GetOK("query")
	if err := o.bindQuery(qQuery, qhkQuery, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindQuery binds and validates array parameter Query from query.
//
// Arrays are parsed according to CollectionFormat: "multi" (defaults to "csv" when empty).
func (o *MassaGetAddressesParams) bindQuery(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("query", "query", rawData)
	}
	// CollectionFormat: multi
	queryIC := rawData
	if len(queryIC) == 0 {
		return errors.Required("query", "query", queryIC)
	}

	var queryIR []string
	for i, queryIV := range queryIC {
		queryI := queryIV

		if err := validate.EnumCase(fmt.Sprintf("%s.%v", "query", i), "query", queryI, []interface{}{"balance"}, true); err != nil {
			return err
		}

		queryIR = append(queryIR, queryI)
	}

	o.Query = queryIR

	return nil
}
