// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/thyra/api/swagger/server/models"
)

// MgmtWalletImportNoContentCode is the HTTP code returned for type MgmtWalletImportNoContent
const MgmtWalletImportNoContentCode int = 204

/*MgmtWalletImportNoContent Wallet imported.

swagger:response mgmtWalletImportNoContent
*/
type MgmtWalletImportNoContent struct {
}

// NewMgmtWalletImportNoContent creates MgmtWalletImportNoContent with default headers values
func NewMgmtWalletImportNoContent() *MgmtWalletImportNoContent {

	return &MgmtWalletImportNoContent{}
}

// WriteResponse to the client
func (o *MgmtWalletImportNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// MgmtWalletImportBadRequestCode is the HTTP code returned for type MgmtWalletImportBadRequest
const MgmtWalletImportBadRequestCode int = 400

/*MgmtWalletImportBadRequest Bad request.

swagger:response mgmtWalletImportBadRequest
*/
type MgmtWalletImportBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMgmtWalletImportBadRequest creates MgmtWalletImportBadRequest with default headers values
func NewMgmtWalletImportBadRequest() *MgmtWalletImportBadRequest {

	return &MgmtWalletImportBadRequest{}
}

// WithPayload adds the payload to the mgmt wallet import bad request response
func (o *MgmtWalletImportBadRequest) WithPayload(payload *models.Error) *MgmtWalletImportBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mgmt wallet import bad request response
func (o *MgmtWalletImportBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MgmtWalletImportBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MgmtWalletImportUnprocessableEntityCode is the HTTP code returned for type MgmtWalletImportUnprocessableEntity
const MgmtWalletImportUnprocessableEntityCode int = 422

/*MgmtWalletImportUnprocessableEntity Unprocessable Entity - syntax is correct, but the server was unable to process the contained instructions.

swagger:response mgmtWalletImportUnprocessableEntity
*/
type MgmtWalletImportUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMgmtWalletImportUnprocessableEntity creates MgmtWalletImportUnprocessableEntity with default headers values
func NewMgmtWalletImportUnprocessableEntity() *MgmtWalletImportUnprocessableEntity {

	return &MgmtWalletImportUnprocessableEntity{}
}

// WithPayload adds the payload to the mgmt wallet import unprocessable entity response
func (o *MgmtWalletImportUnprocessableEntity) WithPayload(payload *models.Error) *MgmtWalletImportUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mgmt wallet import unprocessable entity response
func (o *MgmtWalletImportUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MgmtWalletImportUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MgmtWalletImportInternalServerErrorCode is the HTTP code returned for type MgmtWalletImportInternalServerError
const MgmtWalletImportInternalServerErrorCode int = 500

/*MgmtWalletImportInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response mgmtWalletImportInternalServerError
*/
type MgmtWalletImportInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMgmtWalletImportInternalServerError creates MgmtWalletImportInternalServerError with default headers values
func NewMgmtWalletImportInternalServerError() *MgmtWalletImportInternalServerError {

	return &MgmtWalletImportInternalServerError{}
}

// WithPayload adds the payload to the mgmt wallet import internal server error response
func (o *MgmtWalletImportInternalServerError) WithPayload(payload *models.Error) *MgmtWalletImportInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mgmt wallet import internal server error response
func (o *MgmtWalletImportInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MgmtWalletImportInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
