// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// MgmtWalletGetOneHandlerFunc turns a function with the right signature into a mgmt wallet get one handler
type MgmtWalletGetOneHandlerFunc func(MgmtWalletGetOneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MgmtWalletGetOneHandlerFunc) Handle(params MgmtWalletGetOneParams) middleware.Responder {
	return fn(params)
}

// MgmtWalletGetOneHandler interface for that can handle valid mgmt wallet get one params
type MgmtWalletGetOneHandler interface {
	Handle(MgmtWalletGetOneParams) middleware.Responder
}

// NewMgmtWalletGetOne creates a new http.Handler for the mgmt wallet get one operation
func NewMgmtWalletGetOne(ctx *middleware.Context, handler MgmtWalletGetOneHandler) *MgmtWalletGetOne {
	return &MgmtWalletGetOne{Context: ctx, Handler: handler}
}

/* MgmtWalletGetOne swagger:route GET /mgmt/wallet/{nickname} mgmtWalletGetOne

MgmtWalletGetOne mgmt wallet get one API

*/
type MgmtWalletGetOne struct {
	Context *middleware.Context
	Handler MgmtWalletGetOneHandler
}

func (o *MgmtWalletGetOne) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewMgmtWalletGetOneParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
