// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// MgmtPluginsListHandlerFunc turns a function with the right signature into a mgmt plugins list handler
type MgmtPluginsListHandlerFunc func(MgmtPluginsListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MgmtPluginsListHandlerFunc) Handle(params MgmtPluginsListParams) middleware.Responder {
	return fn(params)
}

// MgmtPluginsListHandler interface for that can handle valid mgmt plugins list params
type MgmtPluginsListHandler interface {
	Handle(MgmtPluginsListParams) middleware.Responder
}

// NewMgmtPluginsList creates a new http.Handler for the mgmt plugins list operation
func NewMgmtPluginsList(ctx *middleware.Context, handler MgmtPluginsListHandler) *MgmtPluginsList {
	return &MgmtPluginsList{Context: ctx, Handler: handler}
}

/*
	MgmtPluginsList swagger:route GET /mgmt/plugins mgmtPluginsList

MgmtPluginsList mgmt plugins list API
*/
type MgmtPluginsList struct {
	Context *middleware.Context
	Handler MgmtPluginsListHandler
}

func (o *MgmtPluginsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewMgmtPluginsListParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
