// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewMyDomainsGetterParams creates a new MyDomainsGetterParams object
//
// There are no default values defined in the spec.
func NewMyDomainsGetterParams() MyDomainsGetterParams {

	return MyDomainsGetterParams{}
}

// MyDomainsGetterParams contains all the bound params for the my domains getter operation
// typically these are obtained from a http.Request
//
// swagger:parameters myDomainsGetter
type MyDomainsGetterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Wallet's short name.
	  Required: true
	  In: path
	*/
	Nickname string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewMyDomainsGetterParams() beforehand.
func (o *MyDomainsGetterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rNickname, rhkNickname, _ := route.Params.GetOK("nickname")
	if err := o.bindNickname(rNickname, rhkNickname, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNickname binds and validates parameter Nickname from path.
func (o *MyDomainsGetterParams) bindNickname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Nickname = raw

	return nil
}
