// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPluginManagerInstallParams creates a new PluginManagerInstallParams object
//
// There are no default values defined in the spec.
func NewPluginManagerInstallParams() PluginManagerInstallParams {

	return PluginManagerInstallParams{}
}

// PluginManagerInstallParams contains all the bound params for the plugin manager install operation
// typically these are obtained from a http.Request
//
// swagger:parameters pluginManagerInstall
type PluginManagerInstallParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*URL from which to retrieve the plug-in.
	  Required: true
	  In: query
	*/
	Source string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPluginManagerInstallParams() beforehand.
func (o *PluginManagerInstallParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSource, qhkSource, _ := qs.GetOK("source")
	if err := o.bindSource(qSource, qhkSource, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSource binds and validates parameter Source from query.
func (o *PluginManagerInstallParams) bindSource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("source", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("source", "query", raw); err != nil {
		return err
	}
	o.Source = raw

	return nil
}
