// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PluginRouterOKCode is the HTTP code returned for type PluginRouterOK
const PluginRouterOKCode int = 200

/*
PluginRouterOK Dumb response. All content and HTTP code are possible for this endpoint.

swagger:response pluginRouterOK
*/
type PluginRouterOK struct {
}

// NewPluginRouterOK creates PluginRouterOK with default headers values
func NewPluginRouterOK() *PluginRouterOK {

	return &PluginRouterOK{}
}

// WriteResponse to the client
func (o *PluginRouterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
