// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PluginManagerInstallHandlerFunc turns a function with the right signature into a plugin manager install handler
type PluginManagerInstallHandlerFunc func(PluginManagerInstallParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PluginManagerInstallHandlerFunc) Handle(params PluginManagerInstallParams) middleware.Responder {
	return fn(params)
}

// PluginManagerInstallHandler interface for that can handle valid plugin manager install params
type PluginManagerInstallHandler interface {
	Handle(PluginManagerInstallParams) middleware.Responder
}

// NewPluginManagerInstall creates a new http.Handler for the plugin manager install operation
func NewPluginManagerInstall(ctx *middleware.Context, handler PluginManagerInstallHandler) *PluginManagerInstall {
	return &PluginManagerInstall{Context: ctx, Handler: handler}
}

/*
	PluginManagerInstall swagger:route POST /plugin-manager pluginManagerInstall

PluginManagerInstall plugin manager install API
*/
type PluginManagerInstall struct {
	Context *middleware.Context
	Handler PluginManagerInstallHandler
}

func (o *PluginManagerInstall) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPluginManagerInstallParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
