// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PluginManagerUninstallHandlerFunc turns a function with the right signature into a plugin manager uninstall handler
type PluginManagerUninstallHandlerFunc func(PluginManagerUninstallParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PluginManagerUninstallHandlerFunc) Handle(params PluginManagerUninstallParams) middleware.Responder {
	return fn(params)
}

// PluginManagerUninstallHandler interface for that can handle valid plugin manager uninstall params
type PluginManagerUninstallHandler interface {
	Handle(PluginManagerUninstallParams) middleware.Responder
}

// NewPluginManagerUninstall creates a new http.Handler for the plugin manager uninstall operation
func NewPluginManagerUninstall(ctx *middleware.Context, handler PluginManagerUninstallHandler) *PluginManagerUninstall {
	return &PluginManagerUninstall{Context: ctx, Handler: handler}
}

/*
	PluginManagerUninstall swagger:route DELETE /plugin-manager/{id} pluginManagerUninstall

PluginManagerUninstall plugin manager uninstall API
*/
type PluginManagerUninstall struct {
	Context *middleware.Context
	Handler PluginManagerUninstallHandler
}

func (o *PluginManagerUninstall) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPluginManagerUninstallParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
