// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPluginRouterParams creates a new PluginRouterParams object
//
// There are no default values defined in the spec.
func NewPluginRouterParams() PluginRouterParams {

	return PluginRouterParams{}
}

// PluginRouterParams contains all the bound params for the plugin router operation
// typically these are obtained from a http.Request
//
// swagger:parameters pluginRouter
type PluginRouterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Author of the plugin.
	  Required: true
	  In: path
	*/
	AuthorName string
	/*Name of the plugin.
	  Required: true
	  In: path
	*/
	PluginName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPluginRouterParams() beforehand.
func (o *PluginRouterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAuthorName, rhkAuthorName, _ := route.Params.GetOK("author-name")
	if err := o.bindAuthorName(rAuthorName, rhkAuthorName, route.Formats); err != nil {
		res = append(res, err)
	}

	rPluginName, rhkPluginName, _ := route.Params.GetOK("plugin-name")
	if err := o.bindPluginName(rPluginName, rhkPluginName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthorName binds and validates parameter AuthorName from path.
func (o *PluginRouterParams) bindAuthorName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.AuthorName = raw

	return nil
}

// bindPluginName binds and validates parameter PluginName from path.
func (o *PluginRouterParams) bindPluginName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.PluginName = raw

	return nil
}
