// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// PutUploadWebWebsiteMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var PutUploadWebWebsiteMaxParseMemory int64 = 32 << 20

// NewPutUploadWebWebsiteParams creates a new PutUploadWebWebsiteParams object
//
// There are no default values defined in the spec.
func NewPutUploadWebWebsiteParams() PutUploadWebWebsiteParams {

	return PutUploadWebWebsiteParams{}
}

// PutUploadWebWebsiteParams contains all the bound params for the put upload web website operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutUploadWebWebsite
type PutUploadWebWebsiteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The file to upload.
	  In: formData
	*/
	Upfile io.ReadCloser
	/*Website's deployer address.
	  Required: true
	  In: path
	*/
	Website string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutUploadWebWebsiteParams() beforehand.
func (o *PutUploadWebWebsiteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(PutUploadWebWebsiteMaxParseMemory); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	upfile, upfileHeader, err := r.FormFile("upfile")
	if err != nil && err != http.ErrMissingFile {
		res = append(res, errors.New(400, "reading file %q failed: %v", "upfile", err))
	} else if err == http.ErrMissingFile {
		// no-op for missing but optional file parameter
	} else if err := o.bindUpfile(upfile, upfileHeader); err != nil {
		res = append(res, err)
	} else {
		o.Upfile = &runtime.File{Data: upfile, Header: upfileHeader}
	}

	rWebsite, rhkWebsite, _ := route.Params.GetOK("website")
	if err := o.bindWebsite(rWebsite, rhkWebsite, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUpfile binds file parameter Upfile.
//
// The only supported validations on files are MinLength and MaxLength
func (o *PutUploadWebWebsiteParams) bindUpfile(file multipart.File, header *multipart.FileHeader) error {
	return nil
}

// bindWebsite binds and validates parameter Website from path.
func (o *PutUploadWebWebsiteParams) bindWebsite(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Website = raw

	return nil
}
