// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ThyraWalletOKCode is the HTTP code returned for type ThyraWalletOK
const ThyraWalletOKCode int = 200

/*
ThyraWalletOK Page found

swagger:response thyraWalletOK
*/
type ThyraWalletOK struct {
}

// NewThyraWalletOK creates ThyraWalletOK with default headers values
func NewThyraWalletOK() *ThyraWalletOK {

	return &ThyraWalletOK{}
}

// WriteResponse to the client
func (o *ThyraWalletOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
