// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewThyraEventsGetterParams creates a new ThyraEventsGetterParams object
//
// There are no default values defined in the spec.
func NewThyraEventsGetterParams() ThyraEventsGetterParams {

	return ThyraEventsGetterParams{}
}

// ThyraEventsGetterParams contains all the bound params for the thyra events getter operation
// typically these are obtained from a http.Request
//
// swagger:parameters thyraEventsGetter
type ThyraEventsGetterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Creator of the transaction that triggered the event.
	  Required: true
	  In: path
	*/
	Caller string
	/*Data content of the event.
	  Required: true
	  In: path
	*/
	Str string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewThyraEventsGetterParams() beforehand.
func (o *ThyraEventsGetterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCaller, rhkCaller, _ := route.Params.GetOK("caller")
	if err := o.bindCaller(rCaller, rhkCaller, route.Formats); err != nil {
		res = append(res, err)
	}

	rStr, rhkStr, _ := route.Params.GetOK("str")
	if err := o.bindStr(rStr, rhkStr, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCaller binds and validates parameter Caller from path.
func (o *ThyraEventsGetterParams) bindCaller(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Caller = raw

	return nil
}

// bindStr binds and validates parameter Str from path.
func (o *ThyraEventsGetterParams) bindStr(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Str = raw

	return nil
}
