// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ThyraHomeHandlerFunc turns a function with the right signature into a thyra home handler
type ThyraHomeHandlerFunc func(ThyraHomeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ThyraHomeHandlerFunc) Handle(params ThyraHomeParams) middleware.Responder {
	return fn(params)
}

// ThyraHomeHandler interface for that can handle valid thyra home params
type ThyraHomeHandler interface {
	Handle(ThyraHomeParams) middleware.Responder
}

// NewThyraHome creates a new http.Handler for the thyra home operation
func NewThyraHome(ctx *middleware.Context, handler ThyraHomeHandler) *ThyraHome {
	return &ThyraHome{Context: ctx, Handler: handler}
}

/*
	ThyraHome swagger:route GET /thyra/home/{resource} thyraHome

ThyraHome thyra home API
*/
type ThyraHome struct {
	Context *middleware.Context
	Handler ThyraHomeHandler
}

func (o *ThyraHome) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewThyraHomeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
