// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewThyraWalletParams creates a new ThyraWalletParams object
// with the default values initialized.
func NewThyraWalletParams() ThyraWalletParams {

	var (
		// initialize parameters with default values

		resourceDefault = string("index.html")
	)

	return ThyraWalletParams{
		Resource: resourceDefault,
	}
}

// ThyraWalletParams contains all the bound params for the thyra wallet operation
// typically these are obtained from a http.Request
//
// swagger:parameters thyraWallet
type ThyraWalletParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Website resource.
	  Required: true
	  In: path
	  Default: "index.html"
	*/
	Resource string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewThyraWalletParams() beforehand.
func (o *ThyraWalletParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rResource, rhkResource, _ := route.Params.GetOK("resource")
	if err := o.bindResource(rResource, rhkResource, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindResource binds and validates parameter Resource from path.
func (o *ThyraWalletParams) bindResource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Resource = raw

	return nil
}
