// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/thyra/api/swagger/server/models"
)

// ThyraHomeOKCode is the HTTP code returned for type ThyraHomeOK
const ThyraHomeOKCode int = 200

/*
ThyraHomeOK Page found

swagger:response thyraHomeOK
*/
type ThyraHomeOK struct {
}

// NewThyraHomeOK creates ThyraHomeOK with default headers values
func NewThyraHomeOK() *ThyraHomeOK {

	return &ThyraHomeOK{}
}

// WriteResponse to the client
func (o *ThyraHomeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ThyraHomeNotFoundCode is the HTTP code returned for type ThyraHomeNotFound
const ThyraHomeNotFoundCode int = 404

/*
ThyraHomeNotFound Resource not found.

swagger:response thyraHomeNotFound
*/
type ThyraHomeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewThyraHomeNotFound creates ThyraHomeNotFound with default headers values
func NewThyraHomeNotFound() *ThyraHomeNotFound {

	return &ThyraHomeNotFound{}
}

// WithPayload adds the payload to the thyra home not found response
func (o *ThyraHomeNotFound) WithPayload(payload *models.Error) *ThyraHomeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the thyra home not found response
func (o *ThyraHomeNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ThyraHomeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
