// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewUploadWebPostParams creates a new UploadWebPostParams object
//
// There are no default values defined in the spec.
func NewUploadWebPostParams() UploadWebPostParams {

	return UploadWebPostParams{}
}

// UploadWebPostParams contains all the bound params for the upload web post operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadWebPost
type UploadWebPostParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*DNS name without '.', capitals letters and specifics characters.
	  Required: true
	  In: path
	*/
	URL string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadWebPostParams() beforehand.
func (o *UploadWebPostParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rURL, rhkURL, _ := route.Params.GetOK("url")
	if err := o.bindURL(rURL, rhkURL, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindURL binds and validates parameter URL from path.
func (o *UploadWebPostParams) bindURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.URL = raw

	return nil
}
