// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadWebPostHandlerFunc turns a function with the right signature into a upload web post handler
type UploadWebPostHandlerFunc func(UploadWebPostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadWebPostHandlerFunc) Handle(params UploadWebPostParams) middleware.Responder {
	return fn(params)
}

// UploadWebPostHandler interface for that can handle valid upload web post params
type UploadWebPostHandler interface {
	Handle(UploadWebPostParams) middleware.Responder
}

// NewUploadWebPost creates a new http.Handler for the upload web post operation
func NewUploadWebPost(ctx *middleware.Context, handler UploadWebPostHandler) *UploadWebPost {
	return &UploadWebPost{Context: ctx, Handler: handler}
}

/* UploadWebPost swagger:route POST /uploadWeb/{dnsname} uploadWebPost

UploadWebPost upload web post API

*/
type UploadWebPost struct {
	Context *middleware.Context
	Handler UploadWebPostHandler
}

func (o *UploadWebPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadWebPostParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
