// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// WebsiteCreatorUploadMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var WebsiteCreatorUploadMaxParseMemory int64 = 32 << 20

// NewWebsiteCreatorUploadParams creates a new WebsiteCreatorUploadParams object
//
// There are no default values defined in the spec.
func NewWebsiteCreatorUploadParams() WebsiteCreatorUploadParams {

	return WebsiteCreatorUploadParams{}
}

// WebsiteCreatorUploadParams contains all the bound params for the website creator upload operation
// typically these are obtained from a http.Request
//
// swagger:parameters websiteCreatorUpload
type WebsiteCreatorUploadParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Address where to deploy website. The account must have been prepare to receive a website.
	  Required: true
	  In: formData
	*/
	Address string
	/*Website contents in a ZIP file.
	  Required: true
	  In: formData
	*/
	Zipfile io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewWebsiteCreatorUploadParams() beforehand.
func (o *WebsiteCreatorUploadParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(WebsiteCreatorUploadMaxParseMemory); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
	fds := runtime.Values(r.Form)

	fdAddress, fdhkAddress, _ := fds.GetOK("address")
	if err := o.bindAddress(fdAddress, fdhkAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	zipfile, zipfileHeader, err := r.FormFile("zipfile")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "zipfile", err))
	} else if err := o.bindZipfile(zipfile, zipfileHeader); err != nil {
		// Required: true
		res = append(res, err)
	} else {
		o.Zipfile = &runtime.File{Data: zipfile, Header: zipfileHeader}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAddress binds and validates parameter Address from formData.
func (o *WebsiteCreatorUploadParams) bindAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("address", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("address", "formData", raw); err != nil {
		return err
	}
	o.Address = raw

	return nil
}

// bindZipfile binds file parameter Zipfile.
//
// The only supported validations on files are MinLength and MaxLength
func (o *WebsiteCreatorUploadParams) bindZipfile(file multipart.File, header *multipart.FileHeader) error {
	return nil
}
