// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewWebsiteCreatorGetterStatusParams creates a new WebsiteCreatorGetterStatusParams object
//
// There are no default values defined in the spec.
func NewWebsiteCreatorGetterStatusParams() WebsiteCreatorGetterStatusParams {

	return WebsiteCreatorGetterStatusParams{}
}

// WebsiteCreatorGetterStatusParams contains all the bound params for the website creator getter status operation
// typically these are obtained from a http.Request
//
// swagger:parameters websiteCreatorGetterStatus
type WebsiteCreatorGetterStatusParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Website creator contract's address
	  Required: true
	  In: path
	*/
	ContractAddress string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewWebsiteCreatorGetterStatusParams() beforehand.
func (o *WebsiteCreatorGetterStatusParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rContractAddress, rhkContractAddress, _ := route.Params.GetOK("contractAddress")
	if err := o.bindContractAddress(rContractAddress, rhkContractAddress, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindContractAddress binds and validates parameter ContractAddress from path.
func (o *WebsiteCreatorGetterStatusParams) bindContractAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ContractAddress = raw

	return nil
}
