// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WebsiteCreatorUploadHandlerFunc turns a function with the right signature into a website creator upload handler
type WebsiteCreatorUploadHandlerFunc func(WebsiteCreatorUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn WebsiteCreatorUploadHandlerFunc) Handle(params WebsiteCreatorUploadParams) middleware.Responder {
	return fn(params)
}

// WebsiteCreatorUploadHandler interface for that can handle valid website creator upload params
type WebsiteCreatorUploadHandler interface {
	Handle(WebsiteCreatorUploadParams) middleware.Responder
}

// NewWebsiteCreatorUpload creates a new http.Handler for the website creator upload operation
func NewWebsiteCreatorUpload(ctx *middleware.Context, handler WebsiteCreatorUploadHandler) *WebsiteCreatorUpload {
	return &WebsiteCreatorUpload{Context: ctx, Handler: handler}
}

/* WebsiteCreatorUpload swagger:route POST /websiteCreator/upload websiteCreatorUpload

WebsiteCreatorUpload website creator upload API

*/
type WebsiteCreatorUpload struct {
	Context *middleware.Context
	Handler WebsiteCreatorUploadHandler
}

func (o *WebsiteCreatorUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewWebsiteCreatorUploadParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
