// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/thyra/api/swagger/server/models"
)

// WebsiteCreatorPutOKCode is the HTTP code returned for type WebsiteCreatorPutOK
const WebsiteCreatorPutOKCode int = 200

/*WebsiteCreatorPutOK New website created.

swagger:response websiteCreatorPutOK
*/
type WebsiteCreatorPutOK struct {

	/*
	  In: Body
	*/
	Payload *models.Websites `json:"body,omitempty"`
}

// NewWebsiteCreatorPutOK creates WebsiteCreatorPutOK with default headers values
func NewWebsiteCreatorPutOK() *WebsiteCreatorPutOK {

	return &WebsiteCreatorPutOK{}
}

// WithPayload adds the payload to the website creator put o k response
func (o *WebsiteCreatorPutOK) WithPayload(payload *models.Websites) *WebsiteCreatorPutOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the website creator put o k response
func (o *WebsiteCreatorPutOK) SetPayload(payload *models.Websites) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebsiteCreatorPutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WebsiteCreatorPutBadRequestCode is the HTTP code returned for type WebsiteCreatorPutBadRequest
const WebsiteCreatorPutBadRequestCode int = 400

/*WebsiteCreatorPutBadRequest Bad request.

swagger:response websiteCreatorPutBadRequest
*/
type WebsiteCreatorPutBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWebsiteCreatorPutBadRequest creates WebsiteCreatorPutBadRequest with default headers values
func NewWebsiteCreatorPutBadRequest() *WebsiteCreatorPutBadRequest {

	return &WebsiteCreatorPutBadRequest{}
}

// WithPayload adds the payload to the website creator put bad request response
func (o *WebsiteCreatorPutBadRequest) WithPayload(payload *models.Error) *WebsiteCreatorPutBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the website creator put bad request response
func (o *WebsiteCreatorPutBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebsiteCreatorPutBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WebsiteCreatorPutUnprocessableEntityCode is the HTTP code returned for type WebsiteCreatorPutUnprocessableEntity
const WebsiteCreatorPutUnprocessableEntityCode int = 422

/*WebsiteCreatorPutUnprocessableEntity Unprocessable Entity - syntax is correct, but the server was unable to process the contained instructions.

swagger:response websiteCreatorPutUnprocessableEntity
*/
type WebsiteCreatorPutUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWebsiteCreatorPutUnprocessableEntity creates WebsiteCreatorPutUnprocessableEntity with default headers values
func NewWebsiteCreatorPutUnprocessableEntity() *WebsiteCreatorPutUnprocessableEntity {

	return &WebsiteCreatorPutUnprocessableEntity{}
}

// WithPayload adds the payload to the website creator put unprocessable entity response
func (o *WebsiteCreatorPutUnprocessableEntity) WithPayload(payload *models.Error) *WebsiteCreatorPutUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the website creator put unprocessable entity response
func (o *WebsiteCreatorPutUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebsiteCreatorPutUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WebsiteCreatorPutInternalServerErrorCode is the HTTP code returned for type WebsiteCreatorPutInternalServerError
const WebsiteCreatorPutInternalServerErrorCode int = 500

/*WebsiteCreatorPutInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response websiteCreatorPutInternalServerError
*/
type WebsiteCreatorPutInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWebsiteCreatorPutInternalServerError creates WebsiteCreatorPutInternalServerError with default headers values
func NewWebsiteCreatorPutInternalServerError() *WebsiteCreatorPutInternalServerError {

	return &WebsiteCreatorPutInternalServerError{}
}

// WithPayload adds the payload to the website creator put internal server error response
func (o *WebsiteCreatorPutInternalServerError) WithPayload(payload *models.Error) *WebsiteCreatorPutInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the website creator put internal server error response
func (o *WebsiteCreatorPutInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebsiteCreatorPutInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
