// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/thyra/api/swagger/server/models"
)

// WebsiteCreatorGetterStatusOKCode is the HTTP code returned for type WebsiteCreatorGetterStatusOK
const WebsiteCreatorGetterStatusOKCode int = 200

/*WebsiteCreatorGetterStatusOK Website creator status retrieved.

swagger:response websiteCreatorGetterStatusOK
*/
type WebsiteCreatorGetterStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.UploadState `json:"body,omitempty"`
}

// NewWebsiteCreatorGetterStatusOK creates WebsiteCreatorGetterStatusOK with default headers values
func NewWebsiteCreatorGetterStatusOK() *WebsiteCreatorGetterStatusOK {

	return &WebsiteCreatorGetterStatusOK{}
}

// WithPayload adds the payload to the website creator getter status o k response
func (o *WebsiteCreatorGetterStatusOK) WithPayload(payload *models.UploadState) *WebsiteCreatorGetterStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the website creator getter status o k response
func (o *WebsiteCreatorGetterStatusOK) SetPayload(payload *models.UploadState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebsiteCreatorGetterStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WebsiteCreatorGetterStatusBadRequestCode is the HTTP code returned for type WebsiteCreatorGetterStatusBadRequest
const WebsiteCreatorGetterStatusBadRequestCode int = 400

/*WebsiteCreatorGetterStatusBadRequest Bad request.

swagger:response websiteCreatorGetterStatusBadRequest
*/
type WebsiteCreatorGetterStatusBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWebsiteCreatorGetterStatusBadRequest creates WebsiteCreatorGetterStatusBadRequest with default headers values
func NewWebsiteCreatorGetterStatusBadRequest() *WebsiteCreatorGetterStatusBadRequest {

	return &WebsiteCreatorGetterStatusBadRequest{}
}

// WithPayload adds the payload to the website creator getter status bad request response
func (o *WebsiteCreatorGetterStatusBadRequest) WithPayload(payload *models.Error) *WebsiteCreatorGetterStatusBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the website creator getter status bad request response
func (o *WebsiteCreatorGetterStatusBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebsiteCreatorGetterStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WebsiteCreatorGetterStatusInternalServerErrorCode is the HTTP code returned for type WebsiteCreatorGetterStatusInternalServerError
const WebsiteCreatorGetterStatusInternalServerErrorCode int = 500

/*WebsiteCreatorGetterStatusInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response websiteCreatorGetterStatusInternalServerError
*/
type WebsiteCreatorGetterStatusInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWebsiteCreatorGetterStatusInternalServerError creates WebsiteCreatorGetterStatusInternalServerError with default headers values
func NewWebsiteCreatorGetterStatusInternalServerError() *WebsiteCreatorGetterStatusInternalServerError {

	return &WebsiteCreatorGetterStatusInternalServerError{}
}

// WithPayload adds the payload to the website creator getter status internal server error response
func (o *WebsiteCreatorGetterStatusInternalServerError) WithPayload(payload *models.Error) *WebsiteCreatorGetterStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the website creator getter status internal server error response
func (o *WebsiteCreatorGetterStatusInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebsiteCreatorGetterStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
